allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: false
  esbuild: true
minimumReleaseAgeExclude:
  - electron@44.4.5
  - esbuild@0.25.0
overrides:
  esbuild@<=0.24.2: 0.25.12
  http-cache-semantics: 4.3.0
  source-map-js: 1.2.2
patchedDependencies:
  sprintf-js@1.1.3: patches/sprintf-js@1.1.3.patch
